services:
  nodecg:
    image: potdig/${LAYOUTS_NAME}
    build:
      context: .
      target: bundle
    profiles:
      - prod
    ports:
      - 9090:9090
  nodecg-dev:
    image: potdig/${LAYOUTS_NAME}
    build:
      context: .
      target: base
    profiles:
      - dev
    volumes:
      - ./dist:/app/nodecg/bundles/${LAYOUTS_NAME}
      - ./node_modules:/app/nodecg/bundles/${LAYOUTS_NAME}/node_modules
      - ./public:/app/nodecg/assets/${LAYOUTS_NAME}/materials
      - ./cfg:/app/nodecg/cfg
    ports:
      - 9090:9090